### ISSUE TITLE
Not engaging at all

### ISSUE THREAD

**Issue by BenComicGraphics** [simplefocus/FlowType.JS#49]
I'm attempting to make this work on red.steadfastlight.com and the base font is not changing value at all.  Help.

**Comment by bphillips201** [comment]
Hi @BenComicGraphics, could you perhaps post a code snippet of how you're initializing FlowType on your page. I see that you're including the JS file in your page. Where do you initialize it?

Example -
```javascript
$('body').flowtype();
```

**Comment by BenComicGraphics** [comment]
I apologize, I got it working :)
