### ISSUE TITLE
Tag specific rules

### ISSUE THREAD

**Issue by MrMegamind** [simplefocus/FlowType.JS#59]
Hi
I just started using your library and took me some time to figure out that I have to use rules to each element. I was just doing the "body" rule and expecting everything to work. Can you please add couple of lines in sample code so new uses can understand they have to use the rule for each unique element.

Thank you for nice library

Peace

**Comment by christhebishop** [comment]
Hello,
Thank you for reaching out. I've updated the README and demo site to include additional clarification and another example in Step 4. 
Thank you

**Comment by MrMegamind** [comment]
Thank you so much, this will be a great help for everyone.
