### ISSUE TITLE
Clashing with other javascript...

### ISSUE THREAD

**Issue by chrisshaw27** [simplefocus/FlowType.JS#60]
I've successfully implemented flowtype.js on some text on a basic html page.
But as soon as I try it on the same text in my website (built from a responsive template)... nothing.

Through trial and error I have narrowed it down to an issue with:
app.js
vendors.js
index.js

As soon as I take the links to these out of my site it works a charm.

Any ideas would be greatly appreciated...
[promlem_js.zip](https://github.com/simplefocus/FlowType.JS/files/625929/promlem_js.zip)

**Comment by christhebishop** [comment]
Hey @chrisshaw27, sorry you're having difficulties. I looked at the files you attached, but I'm not sure at first glance why any of those would be conflicting with FlowType.

Have you tried putting your FlowType javascript below/after all the other javascript files, right before the closing <body> tag? Also, is your site throwing any console errors? Let me know- I'm happy to help!

**Comment by chrisshaw27** [comment]
Thank you christhebishop.

I had the flowtype.js in the head and the " $('#ID').flowtype(); " before the closing body tag.

I simply moved the flowtype.js before the " $('#ID').flowtype(); " (after all of my other js) and it worked perfectly.
